### ISSUE TITLE
合约并发调用时会报错

### ISSUE THREAD

**Issue by ali-pay** [xuperchain/xuper-sdk-go#27]
测试代码：
```go
func TestInvokeWasmContract2(t *testing.T) {
	acc, _ := account.RetrieveAccount(mnemonic, 1)
	wasmContract := InitWasmContract(acc, node, "xuper", "counter", "XC1111111111111111@xuper")

	wg := &sync.WaitGroup{}
	for i := 0; i < 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			txid, err := wasmContract.InvokeWasmContract("increase", map[string]string{"key": "counter"})
			if err != nil {
				t.Log("err:", err)
				return
			}
			t.Log("txid:", txid)
		}()
	}
	wg.Wait()
}
```

错误：
```bash
--- PASS: TestInvokeWasmContract2 (3.82s)
    contract_test.go:191: txid: 958bdd5540491fb90707cecd2b07febb3523a1762cdbd86f2a53a07700d3bd4a
    contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
    contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
    contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
```

**Comment by chaunsin** [comment]
> 测试代码：
> 
> ```go
> func TestInvokeWasmContract2(t *testing.T) {
> 	acc, _ := account.RetrieveAccount(mnemonic, 1)
> 	wasmContract := InitWasmContract(acc, node, "xuper", "counter", "XC1111111111111111@xuper")
> 
> 	wg := &sync.WaitGroup{}
> 	for i := 0; i < 4; i++ {
> 		wg.Add(1)
> 		go func() {
> 			defer wg.Done()
> 			txid, err := wasmContract.InvokeWasmContract("increase", map[string]string{"key": "counter"})
> 			if err != nil {
> 				t.Log("err:", err)
> 				return
> 			}
> 			t.Log("txid:", txid)
> 		}()
> 	}
> 	wg.Wait()
> }
> ```
> 
> 错误：
> 
> ```shell
> --- PASS: TestInvokeWasmContract2 (3.82s)
>     contract_test.go:191: txid: 958bdd5540491fb90707cecd2b07febb3523a1762cdbd86f2a53a07700d3bd4a
>     contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
>     contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
>     contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
> ```

我也碰到了这个错误，请问解决了么？

**Comment by ali-pay** [comment]
> > 测试代码：
> > ```go
> > func TestInvokeWasmContract2(t *testing.T) {
> > 	acc, _ := account.RetrieveAccount(mnemonic, 1)
> > 	wasmContract := InitWasmContract(acc, node, "xuper", "counter", "XC1111111111111111@xuper")
> > 
> > 	wg := &sync.WaitGroup{}
> > 	for i := 0; i < 4; i++ {
> > 		wg.Add(1)
> > 		go func() {
> > 			defer wg.Done()
> > 			txid, err := wasmContract.InvokeWasmContract("increase", map[string]string{"key": "counter"})
> > 			if err != nil {
> > 				t.Log("err:", err)
> > 				return
> > 			}
> > 			t.Log("txid:", txid)
> > 		}()
> > 	}
> > 	wg.Wait()
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 错误：
> > ```shell
> > --- PASS: TestInvokeWasmContract2 (3.82s)
> >     contract_test.go:191: txid: 958bdd5540491fb90707cecd2b07febb3523a1762cdbd86f2a53a07700d3bd4a
> >     contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
> >     contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
> >     contract_test.go:188: err: Failed to post tx: UTXOVM_NOT_FOUND_ERROR
> > ```
> 
> 我也碰到了这个错误，请问解决了么？

用v2版本的sdk

**Comment by chaunsin** [comment]
> 

我用的就是v2的，你那里没有问题？
