### ISSUE TITLE
Remove crypto so dependency from go-sdk

### ISSUE THREAD

**Issue by MichelleZ** [xuperchain/xuper-sdk-go#3]
If a user want to use other languages that he is very good at to interact with our blockchain, he'll can use it in the following ways:
1. He can user our lib that we'll provide in the future
2. Develop his API by the language that he use 

If we don't add this function, a user can't use our lib directly.

**Comment by HawkJing** [comment]
Now this feature has been supported by using crypto/client and conf/sdk.yaml
