### ISSUE TITLE
go sdk编译失败

### ISSUE THREAD

**Issue by Koala-sun** [xuperchain/xuper-sdk-go#51]
make失败，go get github.com/xuperchain/xuper-sdk-go/v2 这个网址404

**Comment by uaanaa** [comment]
需要设置一下代理以连接到64.233.189.141:443

**Comment by uaanaa** [comment]
这个应该是环境问题，可以直接把sdk代码拉下来用，master分支是最新代码

**Comment by Knightsll** [comment]
Hi，请问一下，go get 安装的时候一直报错说没有v2版本，这个情况应该如何解决呀？ @uaanaa

**Comment by uaanaa** [comment]
> Hi，请问一下，go get 安装的时候一直报错说没有v2版本，这个情况应该如何解决呀？ @uaanaa

可以 import  包，然后在goland 中 同步项目依赖关系。

比如：import "github.com/xuperchain/xuper-sdk-go/v2/account"

**Comment by uaanaa** [comment]
你好，这个问题解决了吗？

**Comment by Koala-sun** [comment]
谢谢 我的问题已经解决

**Comment by uaanaa** [comment]
好的，那我关闭这个issues了
