### ISSUE TITLE
功能建议：增加一个xuper地址和evm地址转换的接口

### ISSUE THREAD

**Issue by CyrusLiu158** [xuperchain/xuper-sdk-go#54]
在利用solidity语言开发是，如ERC20、ERC721等，参数会经常传入以太坊0x的40位地址，这与xuper的16位地址不相同。
目前我是通过cli的形式在转换，既然cli已经支持，为什么sdk不加入该接口呢？

**Comment by uaanaa** [comment]
SDK是有该接口的哈，建议看下文档：https://xuper.baidu.com/n/xuperdoc/development_manuals/xuper-sdk/xuper-sdk-go.html

**Comment by CyrusLiu158** [comment]
> https://xuper.baidu.com/n/xuperdoc/development_manuals/xuper-sdk/xuper-sdk-go.html

嗯，go的sdk语言的有，js的没，已经换成go的sdk，感谢~~
