### ISSUE TITLE
建议：SetContractAccount方法不要限制16位，因为要传以太坊地址

### ISSUE THREAD

**Issue by CyrusLiu158** [xuperchain/xuper-sdk-go#55]
account包的SetContractAccount方法，下图逻辑限制了16位，但是某些场景需要传入以太坊地址，由于该字段未export，所以在包外又无法修改
<img width="772" alt="image" src="https://user-images.githubusercontent.com/3727646/169941970-45ea345a-bcb0-476c-a187-d021f5df741e.png">
比如下图合约：
<img width="615" alt="image" src="https://user-images.githubusercontent.com/3727646/169942202-75cb0580-1882-46ff-933b-730648286861.png">
mint方法需要校验合约账户是否为owner，此时需要传入eth的40位地址，而不是xuper的16位地址

**Comment by uaanaa** [comment]
部署在xuperchain 中的 evm 用的也是 xuperchain 中的合约账户，在运行时会转为evm地址。。。。。。。

**Comment by CyrusLiu158** [comment]
> 部署在xuperchain 中的 evm 用的也是 xuperchain 中的合约账户，在运行时会转为evm地址。。。。。。。

不会的呀，你可以试下这个合约，调用mint方法的时候，如果传xuper地址，就会报16位限制的错误。

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/security/Pausable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/// @custom:security-contact dev@yfbudong.com
contract Seatune is ERC20, Pausable, Ownable {
    constructor() ERC20("Seatune", "TUN") {
        _mint(msg.sender, 990000 * 10 ** decimals());
    }

    function pause() public onlyOwner {
        _pause();
    }

    function unpause() public onlyOwner {
        _unpause();
    }

    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }

    function _beforeTokenTransfer(address from, address to, uint256 amount)
        internal
        whenNotPaused
        override
    {
        super._beforeTokenTransfer(from, to, amount);
    }
}

**Comment by uaanaa** [comment]
传的时候参数是什么？ 如果合约方法接收的是 address 类型， 需要用SDK的地址转换接口，转为 evm的地址。
msg.sender， 如果set了contractAccount ，那么就是 合约账户， 如果没有，就是普通账户。

**Comment by CyrusLiu158** [comment]
比如说，如下代码：
acc, err := account.RetrieveAccount("视 巨 戴 暴 兰 储 汪 村 差 位 课 治", 1)
用下面的就会报错：
acc.SetContractAccount(“TeyyPLpp9L7QAcxHangtcHTu7HUZ6iydY”)
如果把SetContractAccount的16位限制的代码注释掉，改用这种就可以
acc.SetContractAccount(“C84299524CC31D052FFC20F07DCE88B36E401A27”)

前者是xuper的地址，后者是转成以太坊的地址

**Comment by CyrusLiu158** [comment]
已解决，如果用xuperIDE创建的合约账户，就会报错，如果用sdk创建的就不会😂
