### ISSUE TITLE
合约event问题

### ISSUE THREAD

**Issue by zhanghe113** [xuperchain/xuper-sdk-go#61]
请问：
1.调用合约返回信息中没有eventlog，那有办法在不使用订阅的情况下知道此次交易是否有eventlog吗？
2.我想同步非挖矿的交易信息，如果使用订阅所有块，返回的信息中只有交易hash，并不能区分出这个交易是出块奖励还是正常的交易，这个有办法吗？

**Comment by uaanaa** [comment]
1. watch  可以过滤到合约与事件级别的监听
2. 要根据交易ID再查询一下交易，交易内的 coinbase 字段为true就是出块奖励。false就是正常交易

**Comment by zhanghe113** [comment]
感谢您的回复，还有些问题
1.我是否可以通过发送交易返回的信息或者查询交易信息判断出此次交易是否有合约日志？
2.使用sdk调用合约方法，此时虽然返回了交易结果，但主干上还未出块，应用时往往是需要确认出块后才能使用结果的，这方面您有相关的经验和建议吗？

**Comment by zhanghe113** [comment]
感谢您的回复，还有些问题
1.我是否可以通过发送交易返回的信息或者查询交易信息判断出此次交易是否有合约日志？
2.使用sdk调用合约方法，此时虽然返回了交易结果，但主干上还未出块，应用时往往是需要确认出块后才能使用结果的，这方面您有相关的经验和建议吗？

**Comment by uaanaa** [comment]
1. 可以关注一下交易的结构
2. 可以看下这个issues：https://github.com/xuperchain/xuper-sdk-go/issues/46

**Comment by zhanghe113** [comment]
> 1. 可以关注一下交易的结构
> 2. 可以看下这个issues：[如何判断一笔交易已经上链 #46](https://github.com/xuperchain/xuper-sdk-go/issues/46)

这个issues我之前阅读过，麻烦再问一下如果订阅block事件后，通过watch接受到的所有交易，是否可以认为交易一定出块成功且一定上链成功，无论底层共识算法是什么？

**Comment by uaanaa** [comment]
> 是否可以认为交易一定出块成功且一定上链成功，无论底层共识算法是什么？

不可以，watch并没有交易确认的逻辑，监听的是符合过滤规则的所有交易。

**Comment by zhanghe113** [comment]
> > 是否可以认为交易一定出块成功且一定上链成功，无论底层共识算法是什么？
> 
> 不可以，watch并没有交易确认的逻辑，监听的是符合过滤规则的所有交易。

好的， 感谢答复
