### ISSUE TITLE
`普通账号`给`合约账号`转账出现：TX_VERIFICATION_ERROR错误

### ISSUE THREAD

**Issue by henly2** [xuperchain/xuper-sdk-go#65]
场景：
1. 使用的链地址（39.156.69.83:37100）
2. 本来想通过SDK部署本地编译的solidity合约到链上，提示`合约账号`UTXO不足；
3. 所以尝试通过`普通账号`给`合约账号`转账一些，结果出现`TX_VERIFICATION_ERROR`的错误？

这个`合约账号`是`普通账号`下的。

请问是什么原因？

**Comment by uaanaa** [comment]
1. 开放网络不允许转账
2. UTXO不足确认下控制台是否有余额
3. 链接开放网络需要开启背书服务，可以看下这篇文档：https://xuper.baidu.com/n/xuperdoc/xuperos/open_network.html

**Comment by henly2** [comment]
1. 我是用普通账号给在普通账号下创建的合约账号转账；如果这也不能转账，那么我没办法通过SDK去部署合约吧？
2. 我的普通账号是有余额的；
3. sdk.yaml里面已经把`isNeedComplianceCheck`和`isNeedComplianceCheckFee`设置成true了；

**Comment by uaanaa** [comment]
1. 开放网络只能使用工作台下载的私钥恢复的账号，是可以创建合约账号的，开放网络默认是从工作台账号扣款的，不需要给合约账户转账

**Comment by henly2** [comment]
好的，多谢回复！
我的目地是，想通过sdk部署本地已经编译好的solidity合约的abi和bin文件；

环境如下：
1. sdk.yaml里面endorseServiceHost: "39.156.69.83:37100"
2. sdk.yaml里面isNeedComplianceCheck和isNeedComplianceCheckFee设置成true
3. 私钥是从工作台导下来的，工作台账号也是有余额的；
4. 合约账号也是从工作台创建的；
5. 想使用SDK来部署本地编译的solidity合约到合约账号下；
6. 结果就是报：Failed to post tx: TX_VERIFICATION_ERROR

在控制台网页是可以在线部署合约的，是SDK不能部署合约吗？还是什么问题？

**Comment by henly2** [comment]
我看到https://github.com/xuperchain/xuper-java-sdk/issues/49这个地方，我把sdk.yaml里面的txVersion从1改成3，就部署成功了。不知道什么限制，总算成功了

**Comment by uaanaa** [comment]
好的， txVersion这个是交易版本限制

**Comment by henly2** [comment]
txVersion改成3，可以了
