### ISSUE TITLE
合约部署消耗fee&gas的问题

### ISSUE THREAD

**Issue by chaunsin** [xuperchain/xuper-sdk-go#72]
请问
在合约部署的时候,我们消耗的gas&fee是使用普通账户里面的资产还是合约账户的资产?另外sdk中option有指定消耗资产选项`WithFeeFromAccount()`,如果不指定该选项,潜在意思是不是说消耗的资产是使用普通账户的资产？
<img width="525" alt="image" src="https://user-images.githubusercontent.com/33649884/200776542-1e4760f7-bc58-4fe8-be34-7122d72e1b53.png">

**Comment by uaanaa** [comment]
是的，在自建链场景下，你理解的没错，但如果是开放网络,消耗的一定是普通账号内的资产。

**Comment by uaanaa** [comment]
你好，该问题解决了吗？
