### ISSUE TITLE
合约调用错误问题

### ISSUE THREAD

**Issue by chaunsin** [xuperchain/xuper-sdk-go#77]
请问,在调用合约得时候出现了这个错误:

<img width="240" alt="image" src="https://github.com/xuperchain/xuper-sdk-go/assets/33649884/69f01301-0f5f-4762-b977-95c22d66b3d9">

请问是什么原因呢？

另外我看这个错误17 对应得枚举值为 `XChainErrorEnum_ROOT_BLOCK_EXIST_ERROR` 请问是不是这个枚举值呢？如何是什么情况下会出现这个错？

<img width="1137" alt="image" src="https://github.com/xuperchain/xuper-sdk-go/assets/33649884/6ae816b3-651d-4c81-92b2-5aac11d8ceb2">

**Comment by superlitian** [comment]
合约执行出错了
